sudo: false

language: ruby

rvm:
  - 2.4.0

branches:
  only:
    - v1_cn

before_install:
  - gem update --system
  - gem install bundler:1.17.1
  - bundle update --bundler

cache: bundler

script: 
  - ./deploy.sh
