sudo: false

language: ruby

rvm:
  - 2.4.0

branches:
  only:
    - v1_cn
    
install:
  - gem uninstall bundler
  - gem install bundler --version '1.17.1'

cache: bundler

script: 
  - ./deploy.sh
